env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust version ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install cargo-nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1

        # https://github.com/gfx-rs/wgpu/blob/110e62aed255777ac635a504ec81029483065be8/.github/workflows/ci.yml#L216
      - name: Run tests
        run: |
          set -e
            cargo llvm-cov --no-cfg-coverage nextest --no-fail-fast --no-report
        shell: bash

      - name: Generate coverage report
        run: |
          set -e
          cargo llvm-cov report --lcov --output-path lcov.info
        shell: bash

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta, nightly, 1.65.0]

name: Rust
on: [push, pull_request]
